In [2]:
import pandas as pd
import numpy as np

In [3]:
df1 = pd.read_csv(r"E:\data\tmdb_movies_backup.csv")
df2 = pd.read_csv(r"E:\data\tmdb_movies_extra_backup.csv")

In [4]:
df1.info()
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86280 entries, 0 to 86279
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movie_id      86280 non-null  int64
 1   title         86280 non-null  object
 2   overview      85996 non-null  object
 3   genres        86280 non-null  object
 4   keywords      86280 non-null  object
 5   cast          86280 non-null  object
 6   director      85752 non-null  object
 7   release_date  86246 non-null  object
 8   runtime       86280 non-null  int64
 9   popularity    86280 non-null  float64
 10  poster_url    85121 non-null  object
dtypes: float64(1), int64(2), object(8)
memory usage: 7.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86276 entries, 0 to 86275
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   movie_id       86276 non-null  int64
 1   budget         86276 non-null  int64
 2   revenue        86276 non-null  int64
 3   tagline        41916 non-null  object
 4   poster_urls    86276 non-null  object
 5   video_keys     86276 non-null  object
 6   review_texts   86276 non-null  object
 7   external_ids   86276 non-null  object
 8   certification  33071 non-null  object
 9   cast           86276 non-null  object
dtypes: int64(3), object(7)
memory usage: 6.6+ MB

In [5]:
df1.duplicated().sum()

np.int64(5)

In [6]:
df1.drop_duplicates(inplace=True)

In [7]:
df2.duplicated().sum()

np.int64(3)

In [8]:
df2.drop_duplicates(inplace=True)

In [9]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 86275 entries, 0 to 86279
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movie_id      86275 non-null  int64
 1   title         86275 non-null  object
 2   overview      85991 non-null  object
 3   genres        86275 non-null  object
 4   keywords      86275 non-null  object
 5   cast          86275 non-null  object
 6   director      85747 non-null  object
 7   release_date  86241 non-null  object
 8   runtime       86275 non-null  int64
 9   popularity    86275 non-null  float64
 10  poster_url    85116 non-null  object
dtypes: float64(1), int64(2), object(8)
memory usage: 7.9+ MB

In [10]:
df1['cast'].head().to_list()

["['Tom Hanks', 'Tim Allen', 'Don Rickles', 'Jim Varney', 'Wallace Shawn']",
 "['Robin Williams', 'Kirsten Dunst', 'Bradley Pierce', 'Bonnie Hunt', 'Jonathan Hyde']",
 "['Walter Matthau', 'Jack Lemmon', 'Ann-Margret', 'Sophia Loren', 'Daryl Hannah']",
 "['Whitney Houston', 'Angela Bassett', 'Loretta Devine', 'Lela Rochon', 'Gregory Hines']",
 "['Steve Martin', 'Diane Keaton', 'Martin Short', 'Kimberly Williams-Paisley', 'George Newbern']"]

In [11]:
df2['cast'].head().to_list()

['[{\'name\': \'Tom Hanks\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/eKF1sGJRrZJbfBG1KirPt1cfNd3.jpg\'}, {\'name\': \'Tim Allen\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/woWhZzFILVhYMAvsPL171HjMY0y.jpg\'}, {\'name\': \'Don Rickles\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/iJLQV4dcbTUgxlWJakjDldzlMXS.jpg\'}, {\'name\': \'Jim Varney\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/zvBFmvKUrPvE6FW35O3RP4i1ZPp.jpg\'}, {\'name\': \'Wallace Shawn\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/wVaM1WlFKDce4esThwL4XtNLhOe.jpg\'}, {\'name\': \'John Ratzenberger\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/oRtDEOuIO1yDhTz5dORBdxXuLMO.jpg\'}, {\'name\': \'Annie Potts\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/hWIzkAH7jkSkxBfwdudxbSPxeno.jpg\'}, {\'name\': \'John Morris\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/lSdNMhN3DoXEQJ37IeOD5mTMUQK.jpg\'}, {\'name\': \'Erik von Detten\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/v0ruIqUUZqXRWTsuui5irfsHMJe.jpg\'}, {\'name\': \'Laurie Metcalf\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/ypAppMZ1Q99cBjtX4BAnZmWjVXe.jpg\'}, {\'name\': \'R. Lee Ermey\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/aXFJlEGHlQT7bwxkKwq6Sx7PeEp.jpg\'}, {\'name\': \'Sarah Freeman\', \'profile_url\': None}, {\'name\': \'Penn Jillette\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/lxMpWaVKyeqZCxENRo1wu13iSTS.jpg\'}, {\'name\': \'Jack Angel\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/5MsVwIULYJotUSbDs61uSJff7ei.jpg\'}, {\'name\': \'Spencer Aste\', \'profile_url\': None}, {\'name\': \'Greg Berg\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/w5Cn5dc9Sci7rTtMfCmIqIJfMjX.jpg\'}, {\'name\': \'Lisa Bradley\', \'profile_url\': None}, {\'name\': \'Kendall Cunningham\', \'profile_url\': None}, {\'name\': \'Debi Derryberry\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/aCVgHnvGBw7ssZA9kl1Pnr5pJjU.jpg\'}, {\'name\': \'Cody Dorkin\', \'profile_url\': None}, {\'name\': \'Bill Farmer\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/lhezx68R12s5Bsv7d77BrQb7tWA.jpg\'}, {\'name\': \'Craig Good\', \'profile_url\': None}, {\'name\': \'Gregory Grudt\', \'profile_url\': None}, {\'name\': \'Danielle Judovits\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/5ecdzR76eyTDcaTGfLOWNeksUi6.jpg\'}, {\'name\': \'Sam Lasseter\', \'profile_url\': None}, {\'name\': \'Brittany Levenbrown\', \'profile_url\': None}, {\'name\': \'Sherry Lynn\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/cp7SYig9JVbBWgc2YD4wEUNQGzh.jpg\'}, {\'name\': \'Scott McAfee\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/meKYkzavWpSg2KheDlMlUmZC4za.jpg\'}, {\'name\': \'Mickie McGowan\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/4K1HF10EvDjdaIoDAnWqFZjnmvk.jpg\'}, {\'name\': "Ryan O\'Donohue", \'profile_url\': None}, {\'name\': \'Jeff Pidgeon\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/t8LV9Y6s1qwQQNSRfo6GWEExffd.jpg\'}, {\'name\': \'Patrick Pinney\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/b0jgxFRdzjwXnmLA0udvjzKEQO2.jpg\'}, {\'name\': \'Phil Proctor\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/wAfx3qAEvcsLpEEIP0zwdhuDIcW.jpg\'}, {\'name\': \'Jan Rabson\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/8IBFupx53arTqxOYhGkGwyVSaOn.jpg\'}, {\'name\': \'Joe Ranft\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/f1BoWC2JbCcfP1e5hKfGsxkHzVU.jpg\'}, {\'name\': \'Andrew Stanton\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/fo6ePCWEVB0L1sccrvB99Iaoqcg.jpg\'}, {\'name\': \'Shane Sweet\', \'profile_url\': \'https://image.tmdb.org/t/p/w500/3fVAoIbfMO2XKtMsIOVpo5fkXVq.jpg\'}]',
 "[{'name': 'Robin Williams', 'profile_url': 'https://image.tmdb.org/t/p/w500/iYdeP6K0qz44Wg2Nw9LPJGMBkQ5.jpg'}, {'name': 'Kirsten Dunst', 'profile_url': 'https://image.tmdb.org/t/p/w500/yhLKGjuiMMdbGnFrR8AREkCZcVF.jpg'}, {'name': 'Bradley Pierce', 'profile_url': 'https://image.tmdb.org/t/p/w500/j6iW0vVA23GQniAPSYI6mi4hiEW.jpg'}, {'name': 'Bonnie Hunt', 'profile_url': 'https://image.tmdb.org/t/p/w500/tT9C6uLztgN8OxJULq6F9iEzqlA.jpg'}, {'name': 'Jonathan Hyde', 'profile_url': 'https://image.tmdb.org/t/p/w500/iNLNW7tH8GRpCP9INLXGmwVU1hK.jpg'}, {'name': 'Bebe Neuwirth', 'profile_url': 'https://image.tmdb.org/t/p/w500/yFOdER8Fc07DU6U3kq2PRcbvDR.jpg'}, {'name': 'David Alan Grier', 'profile_url': 'https://image.tmdb.org/t/p/w500/2BJ2sueZu98fOMZ9Z1tbUzUTxw9.jpg'}, {'name': 'Adam Hann-Byrd', 'profile_url': 'https://image.tmdb.org/t/p/w500/54DcXar17ggNEc5oACCa1pu8rEB.jpg'}, {'name': 'Patricia Clarkson', 'profile_url': 'https://image.tmdb.org/t/p/w500/rHHM9G83fpBAcFathbSyV4Tot5j.jpg'}, {'name': 'Laura Bell Bundy', 'profile_url': 'https://image.tmdb.org/t/p/w500/u2jEH4n630lCXKV9GaUkmRV5vu4.jpg'}, {'name': 'James Handy', 'profile_url': 'https://image.tmdb.org/t/p/w500/j2vG5tc8OcpcKG8eufBEMn2oiqZ.jpg'}, {'name': 'Gillian Barber', 'profile_url': 'https://image.tmdb.org/t/p/w500/9ARa8Bw1s4dZzZyEMHDti8fwPbx.jpg'}, {'name': 'Brandon Obray', 'profile_url': None}, {'name': 'Cyrus Thiedeke', 'profile_url': None}, {'name': 'Gary Joseph Thorup', 'profile_url': None}, {'name': 'Leonard Zola', 'profile_url': None}, {'name': 'Lloyd Berry', 'profile_url': 'https://image.tmdb.org/t/p/w500/12wtrZPPwWrCpMul8k8TbcxQWuU.jpg'}, {'name': 'Malcolm Stewart', 'profile_url': 'https://image.tmdb.org/t/p/w500/eNcMvAYc6AwHeZ8bdBOzja61DvE.jpg'}, {'name': 'Annabel Kershaw', 'profile_url': 'https://image.tmdb.org/t/p/w500/8COfAAk3KLlCAgSgGrRo3OynV9d.jpg'}, {'name': 'Darryl Henriques', 'profile_url': 'https://image.tmdb.org/t/p/w500/sI64BB2hK8Bk4XoPrZjBIgvoHML.jpg'}, {'name': 'Robyn Driscoll', 'profile_url': 'https://image.tmdb.org/t/p/w500/gQMYvrohZUHFe6MquegphThIBgc.jpg'}, {'name': 'Peter Bryant', 'profile_url': 'https://image.tmdb.org/t/p/w500/enc6Lz5tsntLpWGjbzMgOk1DHvv.jpg'}, {'name': 'Sarah Gilson', 'profile_url': None}, {'name': 'Florica Vlad', 'profile_url': None}, {'name': 'June Lion', 'profile_url': None}, {'name': 'Brenda Lockmuller', 'profile_url': None}, {'name': 'Frederick Richardson', 'profile_url': None}, {'name': 'Daniel Olsen', 'profile_url': 'https://image.tmdb.org/t/p/w500/w1Umh4qsAuPzcPsaOKNWCthDR0H.jpg'}, {'name': 'David Szehi', 'profile_url': None}, {'name': 'Tom Woodruff Jr.', 'profile_url': 'https://image.tmdb.org/t/p/w500/o5MW7KiROaA5uf9zzJmpHJfUjh3.jpg'}]",
 "[{'name': 'Walter Matthau', 'profile_url': 'https://image.tmdb.org/t/p/w500/pm1YEQPlsNcHQHZJBgcXvu4U4vg.jpg'}, {'name': 'Jack Lemmon', 'profile_url': 'https://image.tmdb.org/t/p/w500/7jWVWLr1VJqQrN3d4YJaATCIHRw.jpg'}, {'name': 'Ann-Margret', 'profile_url': 'https://image.tmdb.org/t/p/w500/z20lA2EyYbLcZn5GV1deMQDUCEc.jpg'}, {'name': 'Sophia Loren', 'profile_url': 'https://image.tmdb.org/t/p/w500/94Kglg5dsAgOKG76230FFN7m6W3.jpg'}, {'name': 'Daryl Hannah', 'profile_url': 'https://image.tmdb.org/t/p/w500/5FllFmoiaru7tjXJ6Orc11OpQcw.jpg'}, {'name': 'Burgess Meredith', 'profile_url': 'https://image.tmdb.org/t/p/w500/2ozNyIbHChcqIBANwvCDpUZGA9b.jpg'}, {'name': 'Kevin Pollak', 'profile_url': 'https://image.tmdb.org/t/p/w500/jWhKIVtmc3vIoS2l1VsdNwMAMJB.jpg'}, {'name': 'Katie Sagona', 'profile_url': 'https://image.tmdb.org/t/p/w500/P3we4ULnamzzgo8SW3GHChLWcV.jpg'}, {'name': 'Ann Morgan Guilbert', 'profile_url': 'https://image.tmdb.org/t/p/w500/fs0vzZPF62F9rJsMnodPKDo1bUk.jpg'}, {'name': 'James Andelin', 'profile_url': 'https://image.tmdb.org/t/p/w500/3vXPx3CIr1jHoJfT1MZl1lnjLvZ.jpg'}, {'name': 'Marcus Klemp', 'profile_url': None}, {'name': 'Max Wright', 'profile_url': 'https://image.tmdb.org/t/p/w500/bM0yC42RbFCSUWITFGVdiojn7ba.jpg'}, {'name': 'Cheryl Hawker', 'profile_url': 'https://image.tmdb.org/t/p/w500/2noxV9666G25hwxAp4Qydzupz1C.jpg'}, {'name': 'Michelle Johnston', 'profile_url': 'https://image.tmdb.org/t/p/w500/tBW5YIcWNx1ihVcm7nOUiZ9WPOZ.jpg'}]",
 "[{'name': 'Whitney Houston', 'profile_url': 'https://image.tmdb.org/t/p/w500/5su69sRCQReFTS94j2OtcgIQLne.jpg'}, {'name': 'Angela Bassett', 'profile_url': 'https://image.tmdb.org/t/p/w500/tKnuviliyeKNGlo26IU5gIrJAtd.jpg'}, {'name': 'Loretta Devine', 'profile_url': 'https://image.tmdb.org/t/p/w500/cGTQ0X19bkMWqL6O00JK2t6uJBK.jpg'}, {'name': 'Lela Rochon', 'profile_url': 'https://image.tmdb.org/t/p/w500/9DBu3r5O4fBosSS4FnSzFCVpm0O.jpg'}, {'name': 'Gregory Hines', 'profile_url': 'https://image.tmdb.org/t/p/w500/tQDKvHbKAu6Jf90owFAvtYs0ADR.jpg'}, {'name': 'Dennis Haysbert', 'profile_url': 'https://image.tmdb.org/t/p/w500/lcnjaw2CFN6q9eaes1jTYrUB0rb.jpg'}, {'name': 'Mykelti Williamson', 'profile_url': 'https://image.tmdb.org/t/p/w500/dR16zD9AjnHWbeN5OVmJWE0vSax.jpg'}, {'name': 'Michael Beach', 'profile_url': 'https://image.tmdb.org/t/p/w500/7gCBCpK2OSzuUWk5iTZds9NjqkF.jpg'}, {'name': 'Leon', 'profile_url': 'https://image.tmdb.org/t/p/w500/uhLVZV2rH0nnXwQKtsIT0qGsTyg.jpg'}, {'name': 'Wendell Pierce', 'profile_url': 'https://image.tmdb.org/t/p/w500/r6yKahL6Z8l9aUX5qvWxTmWl8Nm.jpg'}, {'name': 'Donald Faison', 'profile_url': 'https://image.tmdb.org/t/p/w500/gNwWP1CHob9Y8fjY69w7EwGxMoz.jpg'}, {'name': 'Jeffrey D. Sams', 'profile_url': 'https://image.tmdb.org/t/p/w500/tEjdUfCEiX7ZrPm2HTGs5Y1Sn7V.jpg'}, {'name': 'Jazz Raycole', 'profile_url': 'https://image.tmdb.org/t/p/w500/6vYRFIDSU2lwUfddCEfYrSLkY6Y.jpg'}, {'name': 'Brandon Hammond', 'profile_url': 'https://image.tmdb.org/t/p/w500/qni4SWV6QLQ302Y8CURsRJ5OP00.jpg'}, {'name': 'Kenya Moore', 'profile_url': 'https://image.tmdb.org/t/p/w500/a4HUrzb8iHDeLC1gKerd9Uyhfxj.jpg'}, {'name': 'Lamont Johnson', 'profile_url': 'https://image.tmdb.org/t/p/w500/49CrcbKnC3hgNwlJfEjtwR4X9rd.jpg'}, {'name': 'Wren T. Brown', 'profile_url': 'https://image.tmdb.org/t/p/w500/vbTHkOhDGbcdB4L7HQF5syxfUJn.jpg'}, {'name': 'Theo', 'profile_url': None}, {'name': 'Ken Love', 'profile_url': None}, {'name': 'Graham Galloway', 'profile_url': None}, {'name': 'Starletta DuPois', 'profile_url': 'https://image.tmdb.org/t/p/w500/pRa261QaUrK03ERYG26QHYCRP0n.jpg'}, {'name': 'Shari L. Carpenter', 'profile_url': None}, {'name': 'Thomas R. Leander', 'profile_url': None}, {'name': 'Cordell Conway', 'profile_url': None}, {'name': 'Lee Wells Jr.', 'profile_url': None}, {'name': 'Hope Brown', 'profile_url': 'https://image.tmdb.org/t/p/w500/icBbUVB15CJ6dvr7w4koMcRCO4W.jpg'}, {'name': 'Delaina Mitchell', 'profile_url': 'https://image.tmdb.org/t/p/w500/hi4piPD7egezP5wYYtd3UoXKj1M.jpg'}, {'name': 'Luis Sharpe', 'profile_url': None}, {'name': 'Joseph S. Myers', 'profile_url': None}, {'name': 'Ezra Swerdlow', 'profile_url': None}, {'name': 'Ellin La Var', 'profile_url': None}, {'name': 'Patricia Anne Fox', 'profile_url': None}, {'name': 'Wally Bujack', 'profile_url': None}, {'name': 'Brenda Baldwin-Davis', 'profile_url': None}, {'name': 'William Bolander', 'profile_url': 'https://image.tmdb.org/t/p/w500/uFtR44zzE3DntOftgKQg7e2n8oC.jpg'}, {'name': 'L. Scott Caldwell', 'profile_url': 'https://image.tmdb.org/t/p/w500/wSBfgHgOrUEUJf8RE3ION1AlhmL.jpg'}, {'name': 'Kacee DeMasi', 'profile_url': None}, {'name': 'Giancarlo Esposito', 'profile_url': 'https://image.tmdb.org/t/p/w500/MJOo4QZgMAb3y8QzOUDVFQusQZ.jpg'}, {'name': 'Wanda-Lee Evans', 'profile_url': None}, {'name': 'Tom Hedrick', 'profile_url': None}, {'name': 'Donyell Hinton', 'profile_url': None}, {'name': 'Bob Huff', 'profile_url': None}, {'name': 'Angela Kenzslowe', 'profile_url': None}, {'name': 'Kelly Preston', 'profile_url': 'https://image.tmdb.org/t/p/w500/kEBLn0igo3OcNgXQ6cpoPTEaIUv.jpg'}, {'name': 'Jose Rosete', 'profile_url': 'https://image.tmdb.org/t/p/w500/7txBc8cYN5babjetfR9Q2Adz8XE.jpg'}, {'name': 'Juliet Rose Serrato', 'profile_url': None}, {'name': 'Wesley Snipes', 'profile_url': 'https://image.tmdb.org/t/p/w500/232tIFkJYkmtQIM31Pi5dmLRR8p.jpg'}]",
 "[{'name': 'Steve Martin', 'profile_url': 'https://image.tmdb.org/t/p/w500/d0KthX8hVWU9BxTCG1QUO8FURRm.jpg'}, {'name': 'Diane Keaton', 'profile_url': 'https://image.tmdb.org/t/p/w500/tnx7pJqisfAzvXOR5wHQsbnH9XH.jpg'}, {'name': 'Martin Short', 'profile_url': 'https://image.tmdb.org/t/p/w500/vWoZIOk7K8TSKu1IN90akswsWjZ.jpg'}, {'name': 'Kimberly Williams-Paisley', 'profile_url': 'https://image.tmdb.org/t/p/w500/eTI5HvnVZoaFgdwERtboGJfREhD.jpg'}, {'name': 'George Newbern', 'profile_url': 'https://image.tmdb.org/t/p/w500/1Xx0K3KGqxyIpL6o2eVQKui86jS.jpg'}, {'name': 'Kieran Culkin', 'profile_url': 'https://image.tmdb.org/t/p/w500/b5EC4nziLhBRX4GOcYx2BdS3FTt.jpg'}, {'name': 'BD Wong', 'profile_url': 'https://image.tmdb.org/t/p/w500/w7Hs9m6ocS2qlibvrLOvmyCKbAN.jpg'}, {'name': 'Peter Michael Goetz', 'profile_url': 'https://image.tmdb.org/t/p/w500/b2a1VpVWLCp1Ux9ipo1SVormkW7.jpg'}, {'name': 'Kate McGregor-Stewart', 'profile_url': 'https://image.tmdb.org/t/p/w500/vsvdAmMZgX85AvnVFd4jigOUipZ.jpg'}, {'name': 'Jane Adams', 'profile_url': 'https://image.tmdb.org/t/p/w500/2FsPAoatMkUZ7khJ9r4Fa7ZxQzS.jpg'}, {'name': 'Eugene Levy', 'profile_url': 'https://image.tmdb.org/t/p/w500/y4CexxKSI6qR5A6PDaD8mSrEhYC.jpg'}, {'name': 'Rebecca Chambers', 'profile_url': None}, {'name': 'April Ortiz', 'profile_url': 'https://image.tmdb.org/t/p/w500/vhLyWRvCTIXszzf1hSLlpDz232u.jpg'}, {'name': 'Dulcy Rogers', 'profile_url': None}, {'name': 'Kathy Anthony', 'profile_url': None}, {'name': 'Adrian Canzoneri', 'profile_url': None}, {'name': 'Lori Alan', 'profile_url': 'https://image.tmdb.org/t/p/w500/cavATg4fX0zAl2MHwlt1IZei7EI.jpg'}, {'name': 'Stephanie Miller', 'profile_url': None}, {'name': 'Hallie Meyers-Shyer', 'profile_url': 'https://image.tmdb.org/t/p/w500/oA6e8WLTgVIjlpVHdcZdaNxbfqF.jpg'}, {'name': 'Jay Wolpert', 'profile_url': None}, {'name': 'Ann Walker', 'profile_url': 'https://image.tmdb.org/t/p/w500/hR48nkt4PERVlrRkO3c9gfkag4m.jpg'}, {'name': 'Sandra Silvestri', 'profile_url': None}, {'name': 'William Akey', 'profile_url': None}, {'name': 'Jonathan Emerson', 'profile_url': None}, {'name': 'Seth Kaplan', 'profile_url': None}, {'name': 'Joshua Duvall Preston', 'profile_url': 'https://image.tmdb.org/t/p/w500/zK7NJcF6LAEVXjyYcnJ1tYlqQjk.jpg'}, {'name': 'K.C. Colwell', 'profile_url': None}, {'name': 'Chase Colwell', 'profile_url': None}, {'name': 'Tony Simotes', 'profile_url': 'https://image.tmdb.org/t/p/w500/2bPXuty1WIQt08RyCm0QatRgMIp.jpg'}, {'name': 'Annie Meyers-Shyer', 'profile_url': None}, {'name': 'Linda DeScenna', 'profile_url': None}, {'name': 'Heidi Averill', 'profile_url': None}, {'name': 'Chelsea Lynn', 'profile_url': None}, {'name': 'Sue Colwell', 'profile_url': None}, {'name': 'Rodrigo Botero', 'profile_url': None}, {'name': 'Vince Lozano', 'profile_url': 'https://image.tmdb.org/t/p/w500/tgUss3KYMqL3BaTh8637kjD4s5k.jpg'}, {'name': 'Caroline Lagerfelt', 'profile_url': 'https://image.tmdb.org/t/p/w500/8ynemfG1ypTk4QCCW4UvwfVNDYi.jpg'}, {'name': 'Ilene Waterstone', 'profile_url': None}, {'name': 'Wendy Worthington', 'profile_url': 'https://image.tmdb.org/t/p/w500/lpS6TxNU5eSaInLbLzbOxwaDEF0.jpg'}, {'name': 'Dorian Spencer', 'profile_url': 'https://image.tmdb.org/t/p/w500/aP3OZAsDjEOKjwn2XT1y4XVrZ7e.jpg'}, {'name': 'Harris Laskawy', 'profile_url': None}, {'name': 'Roxanne Beckford', 'profile_url': 'https://image.tmdb.org/t/p/w500/kgwWB9j9swYEDRFTHkTCLQYWSe5.jpg'}, {'name': 'Valerie Hemmerich', 'profile_url': None}, {'name': 'Peter Spears', 'profile_url': 'https://image.tmdb.org/t/p/w500/6aCVFt5PyIz3MGqwy9jawm6FZS1.jpg'}, {'name': 'Susan Beaubian', 'profile_url': 'https://image.tmdb.org/t/p/w500/q815QuPzyjV5ERLUgQqJOKnonXg.jpg'}, {'name': 'Mychael Bates', 'profile_url': None}, {'name': 'Jerri Rose White', 'profile_url': None}, {'name': 'Shannon Kennedy', 'profile_url': None}, {'name': 'Casey Boersma', 'profile_url': None}, {'name': 'Katie Pierce', 'profile_url': None}, {'name': 'Dylan Boersma', 'profile_url': None}, {'name': 'Jonathan Selstad', 'profile_url': None}, {'name': 'Thomas Selstad', 'profile_url': None}, {'name': 'Christian Boeving', 'profile_url': 'https://image.tmdb.org/t/p/w500/wR5pGjXJAZMUCCSOxtbbcfpSNjQ.jpg'}, {'name': 'Nora Dunn', 'profile_url': 'https://image.tmdb.org/t/p/w500/x9NAUBciKKxDaYRcntc4vKjqilG.jpg'}, {'name': 'David Novak', 'profile_url': 'https://image.tmdb.org/t/p/w500/ti46Z6L98kZjNON20VORm3EoCJj.jpg'}, {'name': 'Kylie Travis', 'profile_url': 'https://image.tmdb.org/t/p/w500/dTNzkovyDrh3QA4XXGRtn1hW5CM.jpg'}]"]

In [12]:
df2['poster_urls'].head().to_list()

["['https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg', 'https://image.tmdb.org/t/p/w500/koUNJtRB1iRKhST9s4itGTzU6lp.jpg', 'https://image.tmdb.org/t/p/w500/q5b86mLRElrbRQf7JBixFZykOA6.jpg', 'https://image.tmdb.org/t/p/w500/1Lxqh5rFjMVMW4BUyGx4wIYQCYx.jpg', 'https://image.tmdb.org/t/p/w500/AptcisAVyZqBllXLEGje8MjKzJI.jpg', 'https://image.tmdb.org/t/p/w500/9Ijv9yyg32mlQbJDYbOoKlWlWbp.jpg', 'https://image.tmdb.org/t/p/w500/fiNp79LUmwhArIpJvbuK4D0LPec.jpg', 'https://image.tmdb.org/t/p/w500/6AafgfifXkFS4g2xGJZIwsPQK6P.jpg', 'https://image.tmdb.org/t/p/w500/bVqDDZlTGFB42ea5kBSEptOhrIO.jpg', 'https://image.tmdb.org/t/p/w500/v9Fr3uof92ZqHt4lLqPA9syK6oA.jpg', 'https://image.tmdb.org/t/p/w500/xkCKS3C7OnTrhMTP0QlISa11NSJ.jpg', 'https://image.tmdb.org/t/p/w500/ifauvhU2ilS3lVeqTi2eh2FUe3o.jpg', 'https://image.tmdb.org/t/p/w500/oLII3pJFSfeLFDKCZbaUIAXEqqz.jpg', 'https://image.tmdb.org/t/p/w500/pb8tdrqMIvFsQSDJoOZLaunIGXw.jpg', 'https://image.tmdb.org/t/p/w500/b5Lzdp4Ku2TzHCDCDNSXXdPaaOI.jpg', 'https://image.tmdb.org/t/p/w500/vbzGEQgjaEAN4xlc27atc03VhDu.jpg', 'https://image.tmdb.org/t/p/w500/t2cblh0eLbkhjsCOLnl3w65XnT8.jpg', 'https://image.tmdb.org/t/p/w500/RyAWIbSmt4xC859hyQ43wUumM9.jpg', 'https://image.tmdb.org/t/p/w500/nxmf3Jm56N2ALONWlIGuZHCvfb1.jpg', 'https://image.tmdb.org/t/p/w500/ogu9yQWekOVpnthatLgBPJD3sjG.jpg', 'https://image.tmdb.org/t/p/w500/qjfVYhvHtSUsfSyBEGFexCR3vhZ.jpg', 'https://image.tmdb.org/t/p/w500/3w33Qv9O4Auy5vbLcaHxcMiCWrZ.jpg', 'https://image.tmdb.org/t/p/w500/9eTdRP1wEZX2JYO7kHNk5yGBbh5.jpg', 'https://image.tmdb.org/t/p/w500/gRLk7XpdRyNa697taDKtFx3l6qV.jpg', 'https://image.tmdb.org/t/p/w500/bOgV0KHd5tPSufZnDWaZctCjJZU.jpg', 'https://image.tmdb.org/t/p/w500/ueEz184G3OuhCG4FttHvdWFPlQ7.jpg', 'https://image.tmdb.org/t/p/w500/hX5TEEzea1XX8t2V9VK5InW4M7x.jpg', 'https://image.tmdb.org/t/p/w500/rqSNdPCgJf1kw9o32RfejOmoIoK.jpg', 'https://image.tmdb.org/t/p/w500/mD39SWZziEwdtyvAVQHPxA4tmNA.jpg', 'https://image.tmdb.org/t/p/w500/fGJwi4mhqg0TaXeqhTayT4OE42E.jpg', 'https://image.tmdb.org/t/p/w500/zWrBShfKEFVBJiOcDiAETmdQBjC.jpg', 'https://image.tmdb.org/t/p/w500/y59d8PjuFSgJJN4VRS7jDoRgSM9.jpg', 'https://image.tmdb.org/t/p/w500/jsL6Sf2LuZmRfWQ2po4unTyykIg.jpg', 'https://image.tmdb.org/t/p/w500/iJbm78MxPjLutWUYixbeege8EVe.jpg', 'https://image.tmdb.org/t/p/w500/tShFke3h1gTP6qBVo1cJ7vSEEPW.jpg', 'https://image.tmdb.org/t/p/w500/4cWLRhub0yY9VJpdw0nqoTPYyiN.jpg', 'https://image.tmdb.org/t/p/w500/uPMDev1i5k4mjRpkehqfbKSlKUU.jpg', 'https://image.tmdb.org/t/p/w500/phl71RCOMfNA5uu1GIYeVxKBYzJ.jpg', 'https://image.tmdb.org/t/p/w500/algsPMfhmXsJRu1CeDfHneuJS2r.jpg', 'https://image.tmdb.org/t/p/w500/9DzjFjtbpiRnENmi6vODaxBgQLZ.jpg', 'https://image.tmdb.org/t/p/w500/wNRat1bU3abQtpInLJW8YxlPsER.jpg', 'https://image.tmdb.org/t/p/w500/zOpj9XcRHKiHzS3z9I7NdTFX48O.jpg', 'https://image.tmdb.org/t/p/w500/iebLOHzoXSrHDO7N6R3ZfvLPMF8.jpg', 'https://image.tmdb.org/t/p/w500/mcgrbPWlE6pUhiyBY1KGKvXOHN0.jpg', 'https://image.tmdb.org/t/p/w500/ghynDOlxfm2AHhrsFxYNcxuKX33.jpg', 'https://image.tmdb.org/t/p/w500/psaRuuIhj9tuw7vL3dAg5DoYbaj.jpg', 'https://image.tmdb.org/t/p/w500/2Z19YpRxntcEQZN02NWWoxbGmAL.jpg', 'https://image.tmdb.org/t/p/w500/oPex50Jk3jUwXfar9B73qoFkca3.jpg', 'https://image.tmdb.org/t/p/w500/21NJ0BtriGMaJX2K4mYTsaHgjqH.jpg', 'https://image.tmdb.org/t/p/w500/k8yiaRgHpWHGjq5Des1T8tId943.jpg', 'https://image.tmdb.org/t/p/w500/rTtFXrAIw0nZJxh6EhBhASrhrU3.jpg', 'https://image.tmdb.org/t/p/w500/5NQHcS7qrhtK6ZL7pql7qyikh4p.jpg', 'https://image.tmdb.org/t/p/w500/7BvxxcvfRVVrP6ITlCQXmeqFWED.jpg', 'https://image.tmdb.org/t/p/w500/nC3YWqBJJ6XdUnviCUFWbyOYdn7.jpg', 'https://image.tmdb.org/t/p/w500/hin5hEEgbjtgW2wUbJAhM9fTzyp.jpg', 'https://image.tmdb.org/t/p/w500/tXAhMF48GYcmzhm45Iw4GDjNnB9.jpg', 'https://image.tmdb.org/t/p/w500/nPjSZmnoSdGLA2mxgccfqVQV78w.jpg', 'https://image.tmdb.org/t/p/w500/dZzu9WZVFRoQxDI5rSZFM8759rk.jpg', 'https://image.tmdb.org/t/p/w500/voln3hFAJwZUgcLdhvDmsjK6Lpq.jpg', 'https://image.tmdb.org/t/p/w500/ah9UVO8YWFts8XdJVa6RWeKdfoW.jpg', 'https://image.tmdb.org/t/p/w500/3ndPtSwyWHpUDqyAuTN82UKkCM7.jpg', 'https://image.tmdb.org/t/p/w500/8j4Hrbm0wpBLXZTvsWf83pk4moV.jpg', 'https://image.tmdb.org/t/p/w500/om4fMx3e4xkx27sAsacoFP4WiEd.jpg', 'https://image.tmdb.org/t/p/w500/45GU1WohfDRIUP0Xn2JBr9WyaXb.jpg', 'https://image.tmdb.org/t/p/w500/9fewYMd61WydJoqmV2HHP5IpuBe.jpg', 'https://image.tmdb.org/t/p/w500/nFhpFCCID55IGiY0TqnaIyQv7OO.jpg', 'https://image.tmdb.org/t/p/w500/jvn7wy3RSNEXnFSXLpH2of2LcV6.jpg', 'https://image.tmdb.org/t/p/w500/p05ZMpMiigegGLqS5XxnmyG15iH.jpg', 'https://image.tmdb.org/t/p/w500/xnZfXjuPOVZOLgbSfEb7YKJxPxC.jpg', 'https://image.tmdb.org/t/p/w500/2y0X1dKnUYhw5sZ2zl1GidawZKL.jpg', 'https://image.tmdb.org/t/p/w500/mSNgm2jO6BdT0L6oCPRQ4anDGEJ.jpg', 'https://image.tmdb.org/t/p/w500/ur4P2Y20CjI7cLOUdEGdNYqVTby.jpg', 'https://image.tmdb.org/t/p/w500/4bxprr56U0bguis9PgjKTLE08KD.jpg', 'https://image.tmdb.org/t/p/w500/7bQ7ystmC3Hn0mplSrNXdBw1CPp.jpg', 'https://image.tmdb.org/t/p/w500/7etkxYqhuifFqa9Y6bjI6RJyFYf.jpg', 'https://image.tmdb.org/t/p/w500/jkiZGcoktAD76koDvD0viam4dCa.jpg', 'https://image.tmdb.org/t/p/w500/GdMDcacJra4ZmDaBIRASIpzjmU.jpg', 'https://image.tmdb.org/t/p/w500/cDmrguhq8TlKCIURp3fOe0ayjG2.jpg', 'https://image.tmdb.org/t/p/w500/7yQ5cSF7y57hug96oAR7f0AV7Jd.jpg', 'https://image.tmdb.org/t/p/w500/6k4MERLbkjQhlQB0b6lNh6bpWnM.jpg', 'https://image.tmdb.org/t/p/w500/6jQzXamv7J7ooxgjPaEF3P3XhNd.jpg', 'https://image.tmdb.org/t/p/w500/iJoWm3laUUsx9ljSSXCHpwslZAD.jpg', 'https://image.tmdb.org/t/p/w500/8ys3D1B8xlTTJjd3B5cd98X6Tqv.jpg', 'https://image.tmdb.org/t/p/w500/4dHDXQjhuLuJyqHoIcZj23oBwng.jpg', 'https://image.tmdb.org/t/p/w500/awcISQJchXGuK3O7iJQG9zKEzCt.jpg', 'https://image.tmdb.org/t/p/w500/qlDGBtphk99VUODnSl1jQxggdlK.jpg', 'https://image.tmdb.org/t/p/w500/9XxMfL0dXH2y1uvmOuIqH5p9gsc.jpg', 'https://image.tmdb.org/t/p/w500/baxVq7cUpBZejKeByrXxgb4cINj.jpg', 'https://image.tmdb.org/t/p/w500/3kGIQJw12JDaDraEuZay4acjGws.jpg', 'https://image.tmdb.org/t/p/w500/qamI8CIV1CRHISXIC5qqbKGXbgJ.jpg', 'https://image.tmdb.org/t/p/w500/gGLmxPCrVH3rZBpnohO53VqMJ8T.jpg', 'https://image.tmdb.org/t/p/w500/bnS8x6iR9sVifz72UW4VceP3wL7.jpg', 'https://image.tmdb.org/t/p/w500/keC4lybjGqshCLEHdzH48Lf1VjF.jpg', 'https://image.tmdb.org/t/p/w500/56B9I9x5bpHUUhknvbJS41BSsh6.jpg', 'https://image.tmdb.org/t/p/w500/mGnOtBmpkQ5CndwxeIKDUqkUkre.jpg', 'https://image.tmdb.org/t/p/w500/c527bh3QM4ItVT3ek5EI7GQOoDR.jpg', 'https://image.tmdb.org/t/p/w500/5ELwzkC7QY9vug20AvRFOXBzLbG.jpg', 'https://image.tmdb.org/t/p/w500/9XFrhkHRYw3AmCZwQX4G2gOwVB0.jpg', 'https://image.tmdb.org/t/p/w500/gmxnC9intmrn1h779L6LFNYN8lj.jpg', 'https://image.tmdb.org/t/p/w500/4KAtscEx3Pt9YPpNuK3BO6irQn1.jpg', 'https://image.tmdb.org/t/p/w500/3dcI9oQ2B1y3fd5HklCcQ1L7xVc.jpg', 'https://image.tmdb.org/t/p/w500/2k5424igOcC1rjJoME8WNREEOgy.jpg', 'https://image.tmdb.org/t/p/w500/4JpZlLR9aNWRVoA3a1X8Mbb7pFW.jpg', 'https://image.tmdb.org/t/p/w500/vWYvwZJniupsyQZkIbGRvLloDCm.jpg', 'https://image.tmdb.org/t/p/w500/6hNy0GvQXWKL3etBePHZHvlSUkf.jpg', 'https://image.tmdb.org/t/p/w500/s3vrlPjbDaDQcvW7JWgMwuYN7f1.jpg', 'https://image.tmdb.org/t/p/w500/tH7iHkbQj2t9UqdkAvoh9zQDaUs.jpg', 'https://image.tmdb.org/t/p/w500/750lugxAXcEi5yeF1y0VavmtXUd.jpg', 'https://image.tmdb.org/t/p/w500/432NFAyLmh1vJb7xH1Dk25ZUIRH.jpg', 'https://image.tmdb.org/t/p/w500/6iYEgLXyL6gLxuC3YBUrU8Lrbkm.jpg', 'https://image.tmdb.org/t/p/w500/zZYkzwifNStTez2fAMOGf8LYiHH.jpg', 'https://image.tmdb.org/t/p/w500/j0xKd4ILEOhVHUYULX3Ix9qdk9M.jpg', 'https://image.tmdb.org/t/p/w500/nI6VHsk6WwagSsvsVTT0Ko8RQLF.jpg', 'https://image.tmdb.org/t/p/w500/zFYTWqyePEtuHzDfD5VCjgOnny2.jpg', 'https://image.tmdb.org/t/p/w500/f3PtcdJNZIVjNsrzfxJzj4z8ZKV.jpg', 'https://image.tmdb.org/t/p/w500/9gVIQbawkR78Rol64IdGBhdBIHP.jpg', 'https://image.tmdb.org/t/p/w500/7KXgUUwtMyjbSHy9lgjP5QfcPWC.jpg', 'https://image.tmdb.org/t/p/w500/15Ml7sD4g0KJtqBTOhc3KFmKt0K.jpg', 'https://image.tmdb.org/t/p/w500/vtyxtEiW1FmRXT09smwrLYPIvNX.jpg', 'https://image.tmdb.org/t/p/w500/3bwJoNhEblFSq3mhQSa13kg7vxd.jpg', 'https://image.tmdb.org/t/p/w500/nq2qdnrPr7gCdNENHfwUm9Dr41T.jpg', 'https://image.tmdb.org/t/p/w500/bhoWbLlQbVwvbESKxwFgF4qyd4l.jpg', 'https://image.tmdb.org/t/p/w500/rsNlvCMXOA7nLFKT38U2GLEpzqm.jpg', 'https://image.tmdb.org/t/p/w500/wMsoU4he62Y7QPTaEovYfpQvazM.jpg', 'https://image.tmdb.org/t/p/w500/jmYJ8is7XduALVttmuh8HvvV9Bi.jpg', 'https://image.tmdb.org/t/p/w500/1qFFOPkMV672Bms2LhVDWbbnsDJ.jpg', 'https://image.tmdb.org/t/p/w500/8xmDvSIbiJmBs7QLtycyG6RMb7i.jpg', 'https://image.tmdb.org/t/p/w500/aIdjya2z2WeqewPvlmuIVTWgFhK.jpg', 'https://image.tmdb.org/t/p/w500/vPlzXwy69JNPOizipQKzE5A2FPK.jpg', 'https://image.tmdb.org/t/p/w500/1wynJzp9xZPgU2mhjLzCBMh19BM.jpg', 'https://image.tmdb.org/t/p/w500/9vQ0yLnZCvm4oT2Jhk7sPelzPUZ.jpg', 'https://image.tmdb.org/t/p/w500/lrhgyIJsaJfRoN9ZAX55CnrcGAV.jpg', 'https://image.tmdb.org/t/p/w500/4Td3UmjMnTeB7DMDiF8d0Ojh7jq.jpg', 'https://image.tmdb.org/t/p/w500/94tkkZYlr35UC4JzrtiACfpF6Ua.jpg', 'https://image.tmdb.org/t/p/w500/mBbYy8XgIFPmGmjIuXKCrOl0qwg.jpg', 'https://image.tmdb.org/t/p/w500/63QsoC52LpEuxGjHJhLQo3xvGPX.jpg', 'https://image.tmdb.org/t/p/w500/sdG9MNVZbYEk2eVsbDiOulMC8N7.jpg', 'https://image.tmdb.org/t/p/w500/rxlosSygAlCHBRC0DKCkr300dk2.jpg', 'https://image.tmdb.org/t/p/w500/hXc7w4SbTB2tFWCdUwggshbzPJT.jpg', 'https://image.tmdb.org/t/p/w500/1mhgCoz4lx5mSdjFzYqnDZUbGNs.jpg', 'https://image.tmdb.org/t/p/w500/9E1UvfLS9PIO9c8TJEOQ7kfFq3Z.jpg', 'https://image.tmdb.org/t/p/w500/oZ6EBjFsJPrqV3GSceTgEy0yOd7.jpg', 'https://image.tmdb.org/t/p/w500/9lR4yIKmYV7bsODqij1IIYa6HRl.jpg', 'https://image.tmdb.org/t/p/w500/cVnFtHyFsza4G5T8AfdQ4JYwKT5.jpg', 'https://image.tmdb.org/t/p/w500/rm7IjJeE9lITBK9Pr7es4nJkDZ9.jpg', 'https://image.tmdb.org/t/p/w500/umLcMhL9pS8f3xhsf86Wb7b2945.jpg', 'https://image.tmdb.org/t/p/w500/qBF1rQgfLVwfZhpo7ti8WAENAD3.jpg', 'https://image.tmdb.org/t/p/w500/sh7ptpTfQb451dxEzJDzyO9B9Fj.jpg', 'https://image.tmdb.org/t/p/w500/dJd7BoaRwZYHOa0ZQQZ7R4cS2gc.jpg', 'https://image.tmdb.org/t/p/w500/bcJqyCyxUFYCFgrT0CVkzMULSip.jpg', 'https://image.tmdb.org/t/p/w500/4niFtDJhZC1u06ZtdXoGQxitlAl.jpg', 'https://image.tmdb.org/t/p/w500/dhN2TjtzZrWUWXHyfI5O6I4cLDN.jpg', 'https://image.tmdb.org/t/p/w500/A2hstQsg4LUAD52aaiqwd3Ul9jX.jpg', 'https://image.tmdb.org/t/p/w500/4hiceMSSdFZbcKdfJBmRKYhXQS2.jpg']",
 "['https://image.tmdb.org/t/p/w500/nLXYV4WmYUF4i8pX0iE0H1rltmf.jpg', 'https://image.tmdb.org/t/p/w500/tszmoRbkPq5qys0eGfE4Rjbn22F.jpg', 'https://image.tmdb.org/t/p/w500/vgpXmVaVyUL7GGiDeiK1mKEKzcX.jpg', 'https://image.tmdb.org/t/p/w500/p67m5dzwyxWd46a6of2c9IVfQz7.jpg', 'https://image.tmdb.org/t/p/w500/v2XHtmVqpERPy0HA1y9wltoeEgW.jpg', 'https://image.tmdb.org/t/p/w500/bdHG5Mo83VPobeZZdlSz0Y7HQHB.jpg', 'https://image.tmdb.org/t/p/w500/6aGn2X51bahFoOI8wE1h2VGTgcH.jpg', 'https://image.tmdb.org/t/p/w500/iWV47r6kFneCiApgrMII5HSkfHw.jpg', 'https://image.tmdb.org/t/p/w500/wysly5f5sJdaVzx89407AWJlHJN.jpg', 'https://image.tmdb.org/t/p/w500/weyXj7sySxB8vfpsAkNuV7Lu5qq.jpg', 'https://image.tmdb.org/t/p/w500/dMnzzrT4wGcr5UexEo3Z3bPWIYo.jpg', 'https://image.tmdb.org/t/p/w500/oqTV8czvCP4hkE7ev2SnJyAEZ2w.jpg', 'https://image.tmdb.org/t/p/w500/87MqqgiT4Pf6x6G1rEA9DLgUCjd.jpg', 'https://image.tmdb.org/t/p/w500/s5jCx2gd29X8JyFqjCsdQVJhIj2.jpg', 'https://image.tmdb.org/t/p/w500/A5wWigmkU5MWShDhHljEuu584UA.jpg', 'https://image.tmdb.org/t/p/w500/z46R8oShx61gXMrAmd7ptpVqNI0.jpg', 'https://image.tmdb.org/t/p/w500/w5JTdGTDnrRlTQ4u0UQxpLe6svE.jpg', 'https://image.tmdb.org/t/p/w500/oaW8hXHOXOMuI8CQVdIQ4sWFSG6.jpg', 'https://image.tmdb.org/t/p/w500/pE0tK6MjBfoxeB4tQcAqYIOCMai.jpg', 'https://image.tmdb.org/t/p/w500/3GxWc4lhXkRhlnjcxPgDcU5u8OA.jpg', 'https://image.tmdb.org/t/p/w500/6qtcLwOQa3UBOLhFOHPkKj6skiX.jpg', 'https://image.tmdb.org/t/p/w500/jCSJgtGKOOeI6qP9hMS0CUchW5f.jpg', 'https://image.tmdb.org/t/p/w500/jgQqsU3voIBv75fzmQtNOzz4tpO.jpg', 'https://image.tmdb.org/t/p/w500/tKtkyGJNGAhF4Fhw7M92MiT0mNK.jpg', 'https://image.tmdb.org/t/p/w500/m67M2wXLKblJLuJlvF7qaGrGfCa.jpg', 'https://image.tmdb.org/t/p/w500/aIq5gjihJnISNkquTBTjDeeDcd9.jpg', 'https://image.tmdb.org/t/p/w500/nD3aHlOkoPwCILMP8ubVfw9H8Gn.jpg', 'https://image.tmdb.org/t/p/w500/YtqQUy9a6kdaem90GdefQ7PkH3.jpg', 'https://image.tmdb.org/t/p/w500/zmjDvC9pbMOj3qst1Yx9JECgd1u.jpg', 'https://image.tmdb.org/t/p/w500/3BFDaG7rR6l9B0THv3Mn7pIjmh8.jpg', 'https://image.tmdb.org/t/p/w500/9ez6swQMA2SIitgqcpBaeQe8Vn3.jpg', 'https://image.tmdb.org/t/p/w500/ftEJqiK00ptMd1QhkWPDmXjACL3.jpg', 'https://image.tmdb.org/t/p/w500/ewmkqH6jmTe2nLm3wPd0UsQ7yMw.jpg', 'https://image.tmdb.org/t/p/w500/jd9wk0i8hwLkMNMAW90GtcJBsVf.jpg', 'https://image.tmdb.org/t/p/w500/2u9aEUBblMCqfDDl8XuayON7TmF.jpg', 'https://image.tmdb.org/t/p/w500/l87SrnqOaPSecHBWZrWHHYVusZQ.jpg', 'https://image.tmdb.org/t/p/w500/5aeZQhMHghOZUK30qNCjgpQlkIq.jpg', 'https://image.tmdb.org/t/p/w500/vWhAtpRlQ0EPlCyZNVwu00jACLB.jpg', 'https://image.tmdb.org/t/p/w500/mgVu6CDj7lrBmgfUo0sfJ45lZa2.jpg', 'https://image.tmdb.org/t/p/w500/wN8Ks9sXJxe54b5nl79oAhWbE3E.jpg', 'https://image.tmdb.org/t/p/w500/8MuwnAwEe6JQwOd7W9y2GW6sWaC.jpg', 'https://image.tmdb.org/t/p/w500/nLpkgA7iS4Lf8AYc1GwGzsJ2OcF.jpg', 'https://image.tmdb.org/t/p/w500/eJW32ZSoDU4ix7693WdDusy7m99.jpg', 'https://image.tmdb.org/t/p/w500/h5nND7nvqZEE8HuzTnGXWqVYi3D.jpg', 'https://image.tmdb.org/t/p/w500/qKSjZpNGKTclOr6sqTrtJNWGFUo.jpg', 'https://image.tmdb.org/t/p/w500/1hoELMKT2huka15VnGQRLsGVbtK.jpg', 'https://image.tmdb.org/t/p/w500/4GzZF1iox2YOMrmTnj1FR7U2V8f.jpg', 'https://image.tmdb.org/t/p/w500/zKYywJb8tGXuau5ZxuEsUfPPrxG.jpg', 'https://image.tmdb.org/t/p/w500/ypbXACSeQeWX0Gi19uSNhdtB0kf.jpg', 'https://image.tmdb.org/t/p/w500/7y56wxz3FV6CoO7DFfSFvPDdbM4.jpg', 'https://image.tmdb.org/t/p/w500/gHgkmPbXsYZYNVNn4aYRX16vDRs.jpg', 'https://image.tmdb.org/t/p/w500/dyVf6IU2wjHAOQhMLN7rwyoL7bk.jpg', 'https://image.tmdb.org/t/p/w500/14MxRsLeYioDSVX1PzDKPVGuBZX.jpg', 'https://image.tmdb.org/t/p/w500/r3h2V4bS1WkQEthBkd0ePG3jFGF.jpg', 'https://image.tmdb.org/t/p/w500/jhNogPPLCGLFfxJABPrkKbsXQj4.jpg', 'https://image.tmdb.org/t/p/w500/neJlktDIg9viYaO2uqyMhNO3B1W.jpg', 'https://image.tmdb.org/t/p/w500/t45K97f2sZTa3iFEDItBEeMMriW.jpg', 'https://image.tmdb.org/t/p/w500/soF08SGrdkL8fd5Vla5gZhyrufY.jpg', 'https://image.tmdb.org/t/p/w500/8Kn6TpfeAlcDr7N7risb4lA1kT7.jpg', 'https://image.tmdb.org/t/p/w500/1eW27UunpNGpa4BlAocbyyHNMPA.jpg', 'https://image.tmdb.org/t/p/w500/azXN9mpIdxCteAQzabFOAHZZiuk.jpg', 'https://image.tmdb.org/t/p/w500/i70LMsGS88ds3JrH9KmIzjXvnxX.jpg', 'https://image.tmdb.org/t/p/w500/jjJohGbwz9kRaf490dZ158vbHho.jpg', 'https://image.tmdb.org/t/p/w500/mrGWLb6vEu7QkVXMI6AtHkZTRpv.jpg', 'https://image.tmdb.org/t/p/w500/64uLq3FMqk0H2kJpQSww3dYSMUq.jpg', 'https://image.tmdb.org/t/p/w500/5hM24wB2Wv125784ogahw9ntzdk.jpg', 'https://image.tmdb.org/t/p/w500/oNwFLmSbXjk6ybvmm082R3CCXCV.jpg', 'https://image.tmdb.org/t/p/w500/sbytkNYHHwr3QAKjHA57YhkxTgh.jpg', 'https://image.tmdb.org/t/p/w500/noua1pvmDJK0Q8Up4Dm0RPpH8nR.jpg', 'https://image.tmdb.org/t/p/w500/2hMWzWcL4l7vyuTLHW4JK1yf621.jpg', 'https://image.tmdb.org/t/p/w500/q17uFcjnmrUSjgTOiwLqhDuLCrr.jpg', 'https://image.tmdb.org/t/p/w500/oPFROPhb6EScNIkLAHDUZMCeWzt.jpg', 'https://image.tmdb.org/t/p/w500/veqaiAvnLq0kwIOFR6HfXINhMjb.jpg', 'https://image.tmdb.org/t/p/w500/cR88OfR2pWEhBHJn2rCEHq1xlTw.jpg', 'https://image.tmdb.org/t/p/w500/2nS6BnWYJyQahBrrq8VBLTKVdgU.jpg', 'https://image.tmdb.org/t/p/w500/nbYekdsqeCsBg6mLPyVIit6GZEc.jpg', 'https://image.tmdb.org/t/p/w500/9sdGCkbwOEAF1JkmfUCCuxlPqPg.jpg', 'https://image.tmdb.org/t/p/w500/cHfIIcumOjNvXMqobR94jCg9sPI.jpg', 'https://image.tmdb.org/t/p/w500/d4qIHzvbdTnooDeJBLLSO4Y0ZQk.jpg']",
 "['https://image.tmdb.org/t/p/w500/1FSXpj5e8l4KH6nVFO5SPUeraOt.jpg', 'https://image.tmdb.org/t/p/w500/y8ZzThQTjdx9Q1sJ0bkApDTvjgU.jpg', 'https://image.tmdb.org/t/p/w500/5xDGSwW2o36qZG3VYi9o5kVFj4i.jpg', 'https://image.tmdb.org/t/p/w500/dMTBXJv5Fer5KJYRek317TmGOA0.jpg', 'https://image.tmdb.org/t/p/w500/mqdczTlOrcjq1dHJbBIlIjOOGVF.jpg', 'https://image.tmdb.org/t/p/w500/iMEtEgZqbVJTEXSEdkbv6QB7PjD.jpg', 'https://image.tmdb.org/t/p/w500/nrbFqeSM1fojZGQWe9zXvdZvkJY.jpg', 'https://image.tmdb.org/t/p/w500/pQ1MS6xBWr2FAE62VLIKVNlTx1f.jpg', 'https://image.tmdb.org/t/p/w500/kbOEjZxZhbIEAiEHpkCmvfDIxS6.jpg', 'https://image.tmdb.org/t/p/w500/liC2coOhJU6ufSVlUOLcXJJOE1e.jpg', 'https://image.tmdb.org/t/p/w500/4wGrG45BhrHjPJypQ3Wzf5Eoz74.jpg', 'https://image.tmdb.org/t/p/w500/zRLjlOwgJtyZCNFmfJIiHjv0NWs.jpg', 'https://image.tmdb.org/t/p/w500/fORLuYL6vUFKo2jguN0eTYMb8dl.jpg', 'https://image.tmdb.org/t/p/w500/p4QAW0KZov9cuMFVhzoDmOudRAl.jpg', 'https://image.tmdb.org/t/p/w500/rLVm0PSGYRhOfQRtYkKXUqKCpyP.jpg', 'https://image.tmdb.org/t/p/w500/wXNAhtwiUclUHwrmZLGLhC5fk52.jpg', 'https://image.tmdb.org/t/p/w500/lNw4rqjPKsjlgJEgwXlF9T2tLZM.jpg', 'https://image.tmdb.org/t/p/w500/p9IbCHMmkSfE95IrcJNCeGKAm1P.jpg', 'https://image.tmdb.org/t/p/w500/8oeLaeXe28ZR2DvRQvcZPCQdGsa.jpg', 'https://image.tmdb.org/t/p/w500/gMimSfbjCxMktsMJpck0tGoIJFE.jpg', 'https://image.tmdb.org/t/p/w500/5DXmwe7d9EHhv5bONEF7ZuFFx6W.jpg', 'https://image.tmdb.org/t/p/w500/1ch0KmnrSrddzDDCw0TQTLdgZH2.jpg', 'https://image.tmdb.org/t/p/w500/kUQs8V6XP1B4BQ84a1LpOZ6gFV.jpg', 'https://image.tmdb.org/t/p/w500/xgkKq6lT0YtdItqP0mZK9m6V7cO.jpg', 'https://image.tmdb.org/t/p/w500/upzJwLh0tyo6t5YX3dAK1zKhl5h.jpg', 'https://image.tmdb.org/t/p/w500/gfw8WDbAHGXc0qNTWF5AuGOoigs.jpg', 'https://image.tmdb.org/t/p/w500/7JAKg0ND3KEfkgKqsjHjcGizFoA.jpg', 'https://image.tmdb.org/t/p/w500/nzKlpzFGiU7N2pY630olbXVR01l.jpg', 'https://image.tmdb.org/t/p/w500/bP9MGHhO5wI7LvElxGyAwQMk1RB.jpg', 'https://image.tmdb.org/t/p/w500/laHAAA5PXp46VsCbHva8nARtsbd.jpg', 'https://image.tmdb.org/t/p/w500/lvy56NeOaXDnW17oaFDd0VhZz32.jpg', 'https://image.tmdb.org/t/p/w500/tYtBurAn0943CHJy4gHVet6ONRB.jpg']",
 "['https://image.tmdb.org/t/p/w500/afLVNPUxvBZ5laBeC4BeuOvTVfD.jpg', 'https://image.tmdb.org/t/p/w500/qJU6rfil5xLVb5HpJsmmfeSK254.jpg', 'https://image.tmdb.org/t/p/w500/8MprEuTY3EwkF9nBBPCUyjRjvs5.jpg', 'https://image.tmdb.org/t/p/w500/bW9HQtmMzpPFiq4bmGkLqFAJs1H.jpg', 'https://image.tmdb.org/t/p/w500/4wjGMwPsdlvi025ZqR4rXnFDvBz.jpg', 'https://image.tmdb.org/t/p/w500/4uw6HKq4vlhrSVp0zkgd4zCy4Pf.jpg', 'https://image.tmdb.org/t/p/w500/kJokIbVDkd6Ywp7IONv8xgfiES7.jpg', 'https://image.tmdb.org/t/p/w500/mIRqwlKWmzdCpnkdnPtlFlYcl0k.jpg', 'https://image.tmdb.org/t/p/w500/w8X78G5nZadNemhIwaNMf5yY8eB.jpg', 'https://image.tmdb.org/t/p/w500/tlMNv7Ghj1SQoD6axxyWIRJlGVX.jpg', 'https://image.tmdb.org/t/p/w500/79o5Sp5eBogI9RdAEi0gzFn1zRt.jpg', 'https://image.tmdb.org/t/p/w500/yZRkWi6gy3aIRzDcXo5EApfG9wN.jpg', 'https://image.tmdb.org/t/p/w500/wvTCKBRkryTQ1gSokqxXE3QywqV.jpg', 'https://image.tmdb.org/t/p/w500/kFXU4a2FWsdfLox8yhqlijKcS8L.jpg', 'https://image.tmdb.org/t/p/w500/x6gR3uo5wct8ThKGx4Clv0YowJP.jpg', 'https://image.tmdb.org/t/p/w500/lyktdDCgqxBDrRvMSIwqk2URC9U.jpg', 'https://image.tmdb.org/t/p/w500/lDio3aGpKADeeeqY2Jq0S0QAUS0.jpg', 'https://image.tmdb.org/t/p/w500/eLL5Gr0VBO5jY4h1LCGzD0vr0tX.jpg', 'https://image.tmdb.org/t/p/w500/g5tQjE0sXKIq151hsfrXoL4un8Q.jpg']",

In [13]:
df1=df1.drop(columns=['cast'])

In [14]:
df1.head()

,movie_id,title,overview,genres,keywords,director,release_date,runtime,popularity,poster_url
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","['Family', 'Comedy', 'Animation', 'Adventure']","['rescue', 'friendship', 'mission', 'jealousy'...",John Lasseter,1995-11-22,81,18.5540,https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5...
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"['Adventure', 'Fantasy', 'Family']","['giant insect', 'board game', 'disappearance'...",Joe Johnston,1995-12-15,104,2.5713,https://image.tmdb.org/t/p/w500/iWV47r6kFneCiA...
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"['Romance', 'Comedy']","['fishing', 'sequel', 'old man', 'best friend'...",Howard Deutch,1995-12-22,101,2.5156,https://image.tmdb.org/t/p/w500/1FSXpj5e8l4KH6...
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","['Comedy', 'Drama', 'Romance']","['based on novel or book', 'single mother', 'd...",Forest Whitaker,1995-12-22,127,3.4707,https://image.tmdb.org/t/p/w500/qJU6rfil5xLVb5...
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,"['Comedy', 'Family']","['daughter', 'baby', 'parent child relationshi...",Charles Shyer,1995-12-08,106,2.9373,https://image.tmdb.org/t/p/w500/rj4LBtwQ0uGrpB...

In [47]:
df2.head()

,movie_id,budget,revenue,tagline,poster_urls,video_keys,review_texts,external_ids,certification,cast
0,862,30000000,394436586,The adventure takes off when toys come to life!,['https://image.tmdb.org/t/p/w500/uXDfjJbdP4ij...,"['_hIfuYVgBrY', 'TZOCUtoygtc', 'CxwTLktovTU', ...","[""This movie came out when I was three. Now I'...","{'id': 862, 'imdb_id': 'tt0114709', 'wikidata_...",G,"[{'name': 'Tom Hanks', 'profile_url': 'https:/..."
1,8844,65000000,262821940,It's a jungle in here.,['https://image.tmdb.org/t/p/w500/nLXYV4WmYUF4...,"['aPkVamOQzVQ', 'BBu-chLYTJ8', '1xKR759ghEw', ...","[""Throw the dice and take a turn, Jumanji made...","{'id': 8844, 'imdb_id': 'tt0113497', 'wikidata...",PG,"[{'name': 'Robin Williams', 'profile_url': 'ht..."
2,15602,25000000,71500000,Still Yelling. Still Fighting. Still Ready for...,['https://image.tmdb.org/t/p/w500/1FSXpj5e8l4K...,['rEnOoWs3FuA'],[],"{'id': 15602, 'imdb_id': 'tt0113228', 'wikidat...",PG-13,"[{'name': 'Walter Matthau', 'profile_url': 'ht..."
3,31357,16000000,81452156,Friends are the people who let you be yourself...,['https://image.tmdb.org/t/p/w500/afLVNPUxvBZ5...,['j9xml1CxgXI'],[],"{'id': 31357, 'imdb_id': 'tt0114885', 'wikidat...",R,"[{'name': 'Whitney Houston', 'profile_url': 'h..."
4,11862,0,76594107,Just when his world is back to normal... he's ...,['https://image.tmdb.org/t/p/w500/rj4LBtwQ0uGr...,['yCg8WNQwe0A'],[],"{'id': 11862, 'imdb_id': 'tt0113041', 'wikidat...",PG,"[{'name': 'Steve Martin', 'profile_url': 'http..."

In [15]:
# we will merge on movie id column
merged_df = pd.merge(df1, df2, on='movie_id', how='inner', suffixes=('_left', '_right'))

In [16]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86273 entries, 0 to 86272
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   movie_id       86273 non-null  int64
 1   title          86273 non-null  object
 2   overview       85989 non-null  object
 3   genres         86273 non-null  object
 4   keywords       86273 non-null  object
 5   director       85745 non-null  object
 6   release_date   86239 non-null  object
 7   runtime        86273 non-null  int64
 8   popularity     86273 non-null  float64
 9   poster_url     85114 non-null  object
 10  budget         86273 non-null  int64
 11  revenue        86273 non-null  int64
 12  tagline        41914 non-null  object
 13  poster_urls    86273 non-null  object
 14  video_keys     86273 non-null  object
 15  review_texts   86273 non-null  object
 16  external_ids   86273 non-null  object
 17  certification  33069 non-null  object
 18  cast           86273 non-null  object
dtypes: float64(1), int64(4), object(14)
memory usage: 12.5+ MB

In [17]:
merged_df.to_csv(r"C:\Users\alyah\VC\first_project\recommendation system\merged_movies.csv", index=False)

In [18]:
df3=pd.read_csv(r"C:\Users\alyah\VC\first_project\recommendation system\modern_movies_2024_2025.csv")

In [19]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9982 entries, 0 to 9981
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   movie_id       9982 non-null   int64
 1   title          9982 non-null   object
 2   overview       9224 non-null   object
 3   genres         9982 non-null   object
 4   keywords       9982 non-null   object
 5   director       9537 non-null   object
 6   release_date   9982 non-null   object
 7   runtime        9982 non-null   int64
 8   popularity     9982 non-null   float64
 9   poster_url     9754 non-null   object
 10  budget         9982 non-null   int64
 11  revenue        9982 non-null   int64
 12  tagline        2760 non-null   object
 13  poster_urls    9982 non-null   object
 14  video_keys     9982 non-null   object
 15  review_texts   9982 non-null   object
 16  external_ids   9982 non-null   object
 17  certification  1849 non-null   object
 18  cast           9982 non-null   object
dtypes: float64(1), int64(4), object(14)
memory usage: 1.4+ MB

In [21]:
df3.duplicated().sum()

np.int64(754)

In [22]:
df3.drop_duplicates(inplace=True)

In [23]:
df3.duplicated().sum()

np.int64(0)

In [24]:
# we will append df3 to merged_df
final_df = pd.concat([merged_df, df3], ignore_index=True)

In [25]:
final_df.to_csv(r"C:\Users\alyah\VC\first_project\recommendation system\movies_DB.csv", index=False)

In [26]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95501 entries, 0 to 95500
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   movie_id       95501 non-null  int64
 1   title          95501 non-null  object
 2   overview       94513 non-null  object
 3   genres         95501 non-null  object
 4   keywords       95501 non-null  object
 5   director       94556 non-null  object
 6   release_date   95467 non-null  object
 7   runtime        95501 non-null  int64
 8   popularity     95501 non-null  float64
 9   poster_url     94133 non-null  object
 10  budget         95501 non-null  int64
 11  revenue        95501 non-null  int64
 12  tagline        44485 non-null  object
 13  poster_urls    95501 non-null  object
 14  video_keys     95501 non-null  object
 15  review_texts   95501 non-null  object
 16  external_ids   95501 non-null  object
 17  certification  34800 non-null  object
 18  cast           95501 non-null  object
dtypes: float64(1), int64(4), object(14)
memory usage: 13.8+ MB

In [71]:
final_df.head()

,movie_id,title,overview,genres,keywords,director,release_date,runtime,popularity,poster_url,budget,revenue,tagline,poster_urls,video_keys,review_texts,external_ids,certification,cast
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","['Family', 'Comedy', 'Animation', 'Adventure']","['rescue', 'friendship', 'mission', 'jealousy'...",John Lasseter,1995-11-22,81,18.554,https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5...,30000000,394436586,The adventure takes off when toys come to life!,['https://image.tmdb.org/t/p/w500/uXDfjJbdP4ij...,"['_hIfuYVgBrY', 'TZOCUtoygtc', 'CxwTLktovTU', ...","[""This movie came out when I was three. Now I'...","{'id': 862, 'imdb_id': 'tt0114709', 'wikidata_...",G,"[{'name': 'Tom Hanks', 'profile_url': 'https:/..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"['Adventure', 'Fantasy', 'Family']","['giant insect', 'board game', 'disappearance'...",Joe Johnston,1995-12-15,104,2.5713,https://image.tmdb.org/t/p/w500/iWV47r6kFneCiA...,65000000,262821940,It's a jungle in here.,['https://image.tmdb.org/t/p/w500/nLXYV4WmYUF4...,"['aPkVamOQzVQ', 'BBu-chLYTJ8', '1xKR759ghEw', ...","[""Throw the dice and take a turn, Jumanji made...","{'id': 8844, 'imdb_id': 'tt0113497', 'wikidata...",PG,"[{'name': 'Robin Williams', 'profile_url': 'ht..."
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"['Romance', 'Comedy']","['fishing', 'sequel', 'old man', 'best friend'...",Howard Deutch,1995-12-22,101,2.5156,https://image.tmdb.org/t/p/w500/1FSXpj5e8l4KH6...,25000000,71500000,Still Yelling. Still Fighting. Still Ready for...,['https://image.tmdb.org/t/p/w500/1FSXpj5e8l4K...,['rEnOoWs3FuA'],[],"{'id': 15602, 'imdb_id': 'tt0113228', 'wikidat...",PG-13,"[{'name': 'Walter Matthau', 'profile_url': 'ht..."
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","['Comedy', 'Drama', 'Romance']","['based on novel or book', 'single mother', 'd...",Forest Whitaker,1995-12-22,127,3.4707,https://image.tmdb.org/t/p/w500/qJU6rfil5xLVb5...,16000000,81452156,Friends are the people who let you be yourself...,['https://image.tmdb.org/t/p/w500/afLVNPUxvBZ5...,['j9xml1CxgXI'],[],"{'id': 31357, 'imdb_id': 'tt0114885', 'wikidat...",R,"[{'name': 'Whitney Houston', 'profile_url': 'h..."
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,"['Comedy', 'Family']","['daughter', 'baby', 'parent child relationshi...",Charles Shyer,1995-12-08,106,2.9373,https://image.tmdb.org/t/p/w500/rj4LBtwQ0uGrpB...,0,76594107,Just when his world is back to normal... he's ...,['https://image.tmdb.org/t/p/w500/rj4LBtwQ0uGr...,['yCg8WNQwe0A'],[],"{'id': 11862, 'imdb_id': 'tt0113041', 'wikidat...",PG,"[{'name': 'Steve Martin', 'profile_url': 'http..."

In [27]:
# now our final DB contains all the movies data merged from three different datasets with over 95,000 records.
# it contains old and modern movies 
# now we will clean and preprocess this data