In [53]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re
import csv

In [54]:
# we will clean our data and make it ready for our website and recommendation system
# we will handle missing values, duplicates, and irrelevant data
df = pd.read_csv(
   r'E:\data\movies_DB.csv')

In [55]:
df.head()

,movie_id,title,overview,genres,keywords,director,release_date,runtime,popularity,poster_url,budget,revenue,tagline,poster_urls,video_keys,review_texts,external_ids,certification,cast
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","['Family', 'Comedy', 'Animation', 'Adventure']","['rescue', 'friendship', 'mission', 'jealousy'...",John Lasseter,1995-11-22,81,18.5540,https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5...,30000000,394436586,The adventure takes off when toys come to life!,['https://image.tmdb.org/t/p/w500/uXDfjJbdP4ij...,"['_hIfuYVgBrY', 'TZOCUtoygtc', 'CxwTLktovTU', ...","[""This movie came out when I was three. Now I'...","{'id': 862, 'imdb_id': 'tt0114709', 'wikidata_...",G,"[{'name': 'Tom Hanks', 'profile_url': 'https:/..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"['Adventure', 'Fantasy', 'Family']","['giant insect', 'board game', 'disappearance'...",Joe Johnston,1995-12-15,104,2.5713,https://image.tmdb.org/t/p/w500/iWV47r6kFneCiA...,65000000,262821940,It's a jungle in here.,['https://image.tmdb.org/t/p/w500/nLXYV4WmYUF4...,"['aPkVamOQzVQ', 'BBu-chLYTJ8', '1xKR759ghEw', ...","[""Throw the dice and take a turn, Jumanji made...","{'id': 8844, 'imdb_id': 'tt0113497', 'wikidata...",PG,"[{'name': 'Robin Williams', 'profile_url': 'ht..."
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"['Romance', 'Comedy']","['fishing', 'sequel', 'old man', 'best friend'...",Howard Deutch,1995-12-22,101,2.5156,https://image.tmdb.org/t/p/w500/1FSXpj5e8l4KH6...,25000000,71500000,Still Yelling. Still Fighting. Still Ready for...,['https://image.tmdb.org/t/p/w500/1FSXpj5e8l4K...,['rEnOoWs3FuA'],[],"{'id': 15602, 'imdb_id': 'tt0113228', 'wikidat...",PG-13,"[{'name': 'Walter Matthau', 'profile_url': 'ht..."
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","['Comedy', 'Drama', 'Romance']","['based on novel or book', 'single mother', 'd...",Forest Whitaker,1995-12-22,127,3.4707,https://image.tmdb.org/t/p/w500/qJU6rfil5xLVb5...,16000000,81452156,Friends are the people who let you be yourself...,['https://image.tmdb.org/t/p/w500/afLVNPUxvBZ5...,['j9xml1CxgXI'],[],"{'id': 31357, 'imdb_id': 'tt0114885', 'wikidat...",R,"[{'name': 'Whitney Houston', 'profile_url': 'h..."
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,"['Comedy', 'Family']","['daughter', 'baby', 'parent child relationshi...",Charles Shyer,1995-12-08,106,2.9373,https://image.tmdb.org/t/p/w500/rj4LBtwQ0uGrpB...,0,76594107,Just when his world is back to normal... he's ...,['https://image.tmdb.org/t/p/w500/rj4LBtwQ0uGr...,['yCg8WNQwe0A'],[],"{'id': 11862, 'imdb_id': 'tt0113041', 'wikidat...",PG,"[{'name': 'Steve Martin', 'profile_url': 'http..."

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95501 entries, 0 to 95500
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   movie_id       95501 non-null  int64
 1   title          95501 non-null  object
 2   overview       94513 non-null  object
 3   genres         95501 non-null  object
 4   keywords       95501 non-null  object
 5   director       94556 non-null  object
 6   release_date   95467 non-null  object
 7   runtime        95501 non-null  int64
 8   popularity     95501 non-null  float64
 9   poster_url     94133 non-null  object
 10  budget         95501 non-null  int64
 11  revenue        95501 non-null  int64
 12  tagline        44485 non-null  object
 13  poster_urls    95501 non-null  object
 14  video_keys     95501 non-null  object
 15  review_texts   95501 non-null  object
 16  external_ids   95501 non-null  object
 17  certification  34800 non-null  object
 18  cast           95501 non-null  object
dtypes: float64(1), int64(4), object(14)
memory usage: 13.8+ MB

In [57]:
# first we will drop irrelevant columns
# videos and images we won't need them  as we will pull them from an API on our website also review texts are not needed 
df.drop(columns=['video_keys','review_texts','poster_urls'],inplace=True)

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95501 entries, 0 to 95500
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   movie_id       95501 non-null  int64
 1   title          95501 non-null  object
 2   overview       94513 non-null  object
 3   genres         95501 non-null  object
 4   keywords       95501 non-null  object
 5   director       94556 non-null  object
 6   release_date   95467 non-null  object
 7   runtime        95501 non-null  int64
 8   popularity     95501 non-null  float64
 9   poster_url     94133 non-null  object
 10  budget         95501 non-null  int64
 11  revenue        95501 non-null  int64
 12  tagline        44485 non-null  object
 13  external_ids   95501 non-null  object
 14  certification  34800 non-null  object
 15  cast           95501 non-null  object
dtypes: float64(1), int64(4), object(11)
memory usage: 11.7+ MB

In [59]:
df.duplicated().sum()

np.int64(0)

In [61]:
df.isnull().sum()

movie_id             0
title                0
overview           988
genres               0
keywords             0
director           945
release_date        34
runtime              0
popularity           0
poster_url        1368
budget               0
revenue              0
tagline          51016
external_ids         0
certification    60701
cast                 0
dtype: int64

In [62]:
df.dtypes

movie_id           int64
title             object
overview          object
genres            object
keywords          object
director          object
release_date      object
runtime            int64
popularity       float64
poster_url        object
budget             int64
revenue            int64
tagline           object
external_ids      object
certification     object
cast              object
dtype: object

In [63]:
col_list=['budget','revenue','runtime','popularity']
for col in col_list:
    x=df[col]==0
    print(f"Number of 0 values in {col}: {df[x].shape[0]}")

Number of 0 values in budget: 78434
Number of 0 values in revenue: 78928
Number of 0 values in runtime: 1981
Number of 0 values in popularity: 96

In [64]:
# we will convert datatypes to appropriate types
# convert release_date to datetime
df['release_date']=pd.to_datetime(df['release_date'],errors='coerce')

In [65]:
df.dtypes

movie_id                  int64
title                    object
overview                 object
genres                   object
keywords                 object
director                 object
release_date     datetime64[ns]
runtime                   int64
popularity              float64
poster_url               object
budget                    int64
revenue                   int64
tagline                  object
external_ids             object
certification            object
cast                     object
dtype: object

In [66]:
list_cols=['genres','keywords',"cast"]
for col in list_cols:
    print(f"{col} : {type(df[col].iloc[0])}")
dict_cols=['external_ids']
for col in dict_cols:
    print(f"{col} : {type(df[col].iloc[0])}")

genres : <class 'str'>
keywords : <class 'str'>
cast : <class 'str'>
external_ids : <class 'str'>

In [67]:
# some column are object but should be lists and some should be dictionaries
# we will convert them using eval
list_cols=['genres','keywords',"cast"]
for col in list_cols:
    df[col]=df[col].apply(lambda x: eval(x) if pd.notnull(x) else x)

dict_cols=['external_ids']
for col in dict_cols:
    df[col]=df[col].apply(lambda x: eval(x) if pd.notnull(x) else x)

In [68]:
# let's check the datatypes again for confirmation to see if we have lists and dictionaries
list_cols=['genres','keywords',"cast"]
for col in list_cols:
    print(f"{col} : {type(df[col].iloc[0])}")
dict_cols=['external_ids']
for col in dict_cols:
    print(f"{col} : {type(df[col].iloc[0])}")

genres : <class 'list'>
keywords : <class 'list'>
cast : <class 'list'>
external_ids : <class 'dict'>

In [69]:
df.dtypes

movie_id                  int64
title                    object
overview                 object
genres                   object
keywords                 object
director                 object
release_date     datetime64[ns]
runtime                   int64
popularity              float64
poster_url               object
budget                    int64
revenue                   int64
tagline                  object
external_ids             object
certification            object
cast                     object
dtype: object

In [70]:
# now our data types are appropriate 
# we got numerics as numeric, dates as datetime, lists as lists, and dictionaries as dictionaries
# python pandas will still show lists and dictionaries as objects but they are now in the correct format as objects could be anything (string, int, list, dict, etc) not number or date
# also we got string columns as object which is correct (overview,title,tagline,etc)
# next we will handle missing values
df.isnull().sum()

movie_id             0
title                0
overview           988
genres               0
keywords             0
director           945
release_date        34
runtime              0
popularity           0
poster_url        1368
budget               0
revenue              0
tagline          51016
external_ids         0
certification    60701
cast                 0
dtype: int64

In [71]:
# overview we will fill na with "No overview available" for tagline we will fill na with ""  so it be blank if no tagline is available
# for release_date since it's datetime we will leave it as and for dispaly purposes we will handle it on the website side making it "Unknown" if nat
# for poster_url we will use "" so on the website we can show a placeholder image if no url is available 
# which is better than na as nan requires special handling on the website side we will need use pd.isna() to check for nan values so using empty string is easier to handle on the website side
# for director we will fill na with "Unknown" for certification we will fill na with "N/A"
df['overview'] = df['overview'].fillna("No overview available")
df['tagline'] = df['tagline'].fillna("")
df['director'] = df['director'].fillna("Unknown")
df['certification'] = df['certification'].fillna("N/A")
df['poster_url'] = df['poster_url'].fillna("")

In [72]:
df.isnull().sum()

movie_id          0
title             0
overview          0
genres            0
keywords          0
director          0
release_date     34
runtime           0
popularity        0
poster_url        0
budget            0
revenue           0
tagline           0
external_ids      0
certification     0
cast              0
dtype: int64

In [73]:
# now our data has no missing values except for release_date which we will handle on the website side

In [74]:
list_cols=['genres','keywords',"cast",'external_ids']
for col in list_cols:
    x=df[df[col].apply(len) == 0]
    print(f"Number of rows with empty {col}: {x.shape[0]}")
# some movies have no genres, keywords, cast which is expected especially for less popular movies or old movies
# also we dont have a lot of empty lists so we will keep them as is even for keywords as its expected some movies have no keywords

Number of rows with empty genres: 1318
Number of rows with empty keywords: 28996
Number of rows with empty cast: 3554
Number of rows with empty external_ids: 0

In [75]:
df.describe()

,movie_id,release_date,runtime,popularity,budget,revenue
count,9.550100e+04,95467,95501.000000,95501.000000,9.550100e+04,9.550100e+04
mean,3.407858e+05,1998-09-13 09:37:53.309101696,90.098858,1.978762,3.044721e+06,8.062711e+06
min,2.000000e+00,1874-12-09 00:00:00,0.000000,0.000000,0.000000e+00,0.000000e+00
25%,5.204700e+04,1985-05-11 12:00:00,82.000000,0.805600,0.000000e+00,0.000000e+00
50%,1.777140e+05,2008-09-12 00:00:00,93.000000,1.525900,0.000000e+00,0.000000e+00
75%,4.799700e+05,2017-11-24 00:00:00,105.000000,2.511500,0.000000e+00,0.000000e+00
max,1.594337e+06,2025-12-31 00:00:00,12480.000000,446.114800,5.839000e+08,2.923706e+09
std,3.919967e+05,NaN,52.918092,4.150434,1.535722e+07,5.730791e+07

In [76]:
df.shape

(95501, 16)

In [77]:
df.isnull().sum()

movie_id          0
title             0
overview          0
genres            0
keywords          0
director          0
release_date     34
runtime           0
popularity        0
poster_url        0
budget            0
revenue           0
tagline           0
external_ids      0
certification     0
cast              0
dtype: int64

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95501 entries, 0 to 95500
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   movie_id       95501 non-null  int64
 1   title          95501 non-null  object
 2   overview       95501 non-null  object
 3   genres         95501 non-null  object
 4   keywords       95501 non-null  object
 5   director       95501 non-null  object
 6   release_date   95467 non-null  datetime64[ns]
 7   runtime        95501 non-null  int64
 8   popularity     95501 non-null  float64
 9   poster_url     95501 non-null  object
 10  budget         95501 non-null  int64
 11  revenue        95501 non-null  int64
 12  tagline        95501 non-null  object
 13  external_ids   95501 non-null  object
 14  certification  95501 non-null  object
 15  cast           95501 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(4), object(10)
memory usage: 11.7+ MB

In [79]:
col=['movie_id']
df[col].duplicated().sum()

np.int64(56)

In [80]:
# drop duplicates based on movie_id
df.drop_duplicates(subset=col,inplace=True)

In [99]:
# now our data is clean and we addressed missing values and removed duplicates and irrelevant columns also we converted datatypes to appropriate types
# our data base is ready for website and recommendation system
# we will save it to a new csv file we will use jason format for columns with lists and dictionaries so we can read them back easily
import json

list_dict_cols = ['genres', 'keywords', 'cast', 'external_ids']
for col in list_dict_cols:
    df[col] = df[col].apply(lambda x: json.dumps(x))

df.to_csv(r'C:\Users\alyah\VC\first_project\recommendation system\movies_DB_cleaned.csv', index=False)